openapi: 3.0.1
info:
  title: Ainized-ChatLearner
  contact:
    email: hojun@comcom.ai
  version: 0.0.1
servers:
    - url: 'https://chatlearner.minho-comcom-ai.endpoint.ainize.ai'
paths:
  /chatbot:
    get:
      tags:
      - ChatLearner
      summary: request to reply the sentences ...
      parameters:
      - name: sentence
        in: query
        description: give me sentence
        required: true
        schema:
          type: string
          default: Hello.
      - name: previous_session_id
        in: query
        description: positive integer for knowledge sharing. (currently, only for single instance scope.)
        schema:
          type: integer
      responses:
        200:
          description: Success!
          content:
            application/json:
              schema:
                type: object
                properties:
                  question:
                    type: string
                  answer:
                    type: string
                  current_session_id:
                    type: integer
                  okay:
                    type: boolean
